### ISSUE TITLE
I finished the block calculation, but a new problem appeared.

### ISSUE THREAD

**Issue by WangYu0611** [DekuLiuTesla/CityGaussian#18]
I encountered a new problem, but this time I completed the calculation of the results of the block calculation, and I feel that the effect is very good.
![屏幕截图 2024-08-22 140604](https://github.com/user-attachments/assets/05ee97d5-8eee-40a4-b9be-2c75e8c39ff0)
![屏幕截图 2024-08-22 140616](https://github.com/user-attachments/assets/17730bb5-df7d-4f5d-ba35-688952c8a2da)

But when I calculated and merged all the blocks, new errors appeared.

1.AssertionError: Could not recognize scene type!
```
Saving merged 23765873 point cloud to output/mc_aerial_c36/point_cloud/iteration_30000/point_cloud.ply
Done
GPU 0 is available.
Loading trained model at iteration 30000 [22/08 13:42:33]
Traceback (most recent call last):
  File "/home/server9/CityGaussian/render_large.py", line 139, in <module>
    render_sets(lp, args.iteration, pp, args.load_vq, args.skip_train, args.skip_test, args.custom_test)
  File "/home/server9/CityGaussian/render_large.py", line 93, in render_sets
    scene = LargeScene(dataset, gaussians, load_iteration=iteration, load_vq=load_vq, shuffle=False)
  File "/home/server9/CityGaussian/scene/__init__.py", line 136, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```
I checked scene/_init_.py，found source_path: "data/matrix_city/aerial/train/block_all",
there is only one transforms.json file in the file directory, and there seems to be no 
`if os.path.exists(os.path.join(args.source_path, "sparse")): scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval, partition=partition) elif os.path.exists(os.path.join(args.source_path, "transforms_train.json")): print("Found transforms_train.json file, assuming Blender data set!") scene_info = sceneLoadTypeCallbacks["Blender"](args.source_path, args.white_background, args.eval) else: assert False, "Could not recognize scene type!"`

I am not sure about the file with the name transforms_train.json. Even if I change the file name, it will still report an error.

2.FileNotFoundError: [Errno 2] No such file or directory: 'output/mc_aerial_c36/test'
```
Scene: output/mc_aerial_c36
Traceback (most recent call last):
  File "/home/server9/CityGaussian/metrics_large.py", line 118, in <module>
    evaluate(args.model_paths, args.test_sets, args.correct_color)
  File "/home/server9/CityGaussian/metrics_large.py", line 55, in evaluate
    for method in os.listdir(test_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'output/mc_aerial_c36/test'
```
I changed out_name="test" in the run_citys.py code to this, but it still reports an error. I'm not sure if it's because the previous step was not executed successfully, or if it's because of some other reason. And there is indeed no test folder in the output/mc_aerial_c36 directory.

**Comment by WangYu0611** [comment]
pls help me @DekuLiuTesla

**Comment by WangYu0611** [comment]
I solved this problem after reading the data document.

> pls help me @DekuLiuTesla

I solved this problem after reading the data document.
