### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'  //No such file or directory: 'output/rubble_coarse/point_cloud/iteration_30000/point_cloud.ply'

### ISSUE THREAD

**Issue by JCpeny** [DekuLiuTesla/CityGaussian#40]
_________________________________________________________________________________________________________________________________________
Training progress:  23%|████████████████████████▋                                                                                 | 7000/30000 [08:40<20:05, 19.09it/s, Loss=0.1434757]Traceback (most recent call last):
  File "/data/kongsujie/CityGaussian/train_large.py", line 309, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/kongsujie/CityGaussian/train_large.py", line 141, in training
    training_report(dataset, log_writer, image_logger, iteration, Ll1, loss, l1_loss, ema_time, lr,
  File "/data/kongsujie/CityGaussian/train_large.py", line 260, in training_report
    image_logger(
  File "/data/kongsujie/CityGaussian/utils/log_utils.py", line 4, in tensorboard_log_image
    log_writer.experiment.add_image(
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 614, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/torch/utils/tensorboard/summary.py", line 441, in image
    image = make_image(tensor, rescale=rescale)
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/torch/utils/tensorboard/summary.py", line 486, in make_image
    image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Training progress:  23%|████████████████████████▋                                                                                 | 7000/30000 [08:42<28:35, 13.41it/s, Loss=0.1434757]
GPU 0 is available.
Output folder: ./output/rubble_c9_r4 [19/09 23:26:44]
Reading camera 1657/1657 [19/09 23:26:51]
Train cameras: 1657, Test cameras: 0 [19/09 23:26:51]
Traceback (most recent call last):
  File "/data/kongsujie/CityGaussian/data_partition.py", line 151, in <module>
    scene = LargeScene(lp, gaussians, shuffle=False)
  File "/data/kongsujie/CityGaussian/scene/__init__.py", line 168, in __init__
    self.gaussians.load_ply(os.path.join(self.pretrain_path, "point_cloud.ply"))
  File "/data/kongsujie/CityGaussian/scene/gaussian_model.py", line 229, in load_ply
    plydata = PlyData.read(path)
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/plyfile.py", line 401, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/plyfile.py", line 481, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: 'output/rubble_coarse/point_cloud/iteration_30000/point_cloud.ply'
GPU 0 is available. Starting training block '0'
Optimizing 
Output folder: ./output/rubble_c9_r4/cells/cell0 [19/09 23:26:56]
Traceback (most recent call last):
  File "/data/kongsujie/CityGaussian/train_large.py", line 309, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/kongsujie/CityGaussian/train_large.py", line 43, in training
    scene = LargeScene(dataset, gaussians)
  File "/data/kongsujie/CityGaussian/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/mill19/rubble-pixsfm/train/data_partitions/rubble_c9_r4.npy'
GPU 0 is available. Starting training block '1'
Optimizing 
Output folder: ./output/rubble_c9_r4/cells/cell1 [19/09 23:28:55]
Traceback (most recent call last):
  File "/data/kongsujie/CityGaussian/train_large.py", line 309, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/kongsujie/CityGaussian/train_large.py", line 43, in training
    scene = LargeScene(dataset, gaussians)
  File "/data/kongsujie/CityGaussian/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/mill19/rubble-pixsfm/train/data_partitions/rubble_c9_r4.npy'
GPU 0 is available. Starting training block '2'
Optimizing 
Output folder: ./output/rubble_c9_r4/cells/cell2 [19/09 23:30:55]
Traceback (most recent call last):
  File "/data/kongsujie/CityGaussian/train_large.py", line 309, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/kongsujie/CityGaussian/train_large.py", line 43, in training
    scene = LargeScene(dataset, gaussians)
  File "/data/kongsujie/CityGaussian/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/mill19/rubble-pixsfm/train/data_partitions/rubble_c9_r4.npy'
GPU 0 is available. Starting training block '3'
Optimizing 
Output folder: ./output/rubble_c9_r4/cells/cell3 [19/09 23:32:55]
Traceback (most recent call last):
  File "/data/kongsujie/CityGaussian/train_large.py", line 309, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/kongsujie/CityGaussian/train_large.py", line 43, in training
    scene = LargeScene(dataset, gaussians)
  File "/data/kongsujie/CityGaussian/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/data/kongsujie/miniconda3/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/mill19/rubble-pixsfm/train/data_partitions/rubble_c9_r4.npy'
......

_____________________________________________________________________________________________________________________________________________

Hello, when I use "bash scripts/run_citygs.sh",its traceback like these above.

and I get “output” like this.
![image](https://github.com/user-attachments/assets/7dbb2e24-b628-4b19-9e2f-c4a4932ccd2e)

this is my "data" folder
![image](https://github.com/user-attachments/assets/9c724f66-96b5-4537-82a2-092b645a8e60)
I renamed the "rgbs" with "images"

I wonder why this is happening and how to resolve it.

**Comment by ArSpi** [comment]
It looks like that some errors about `PIL` module occured when the program was saving the rendering images to tensorboard using the trained 7000 model. It is suggested to check your conda environment or reinstall the environment.

**Comment by JCpeny** [comment]
> try to change the version of Pillow: pip install Pillow==9.5.0尝试更改Pillow的版本：pip install Pillow==9.5.0

yes, it works, i solved the error today,thank you!
