### ISSUE TITLE
run_vectree_quantize_rubble.sh

### ISSUE THREAD

**Issue by DuHao55** [DekuLiuTesla/CityGaussian#47]
Hey, I'm running run_vectree_quantize_rubble.sh and it reports the following error.

Traceback (most recent call last):
  File "/storage/public/home/2022032005/PycharmProject/CityGaussian/LargeLightGaussian/large_prune_finetune.py", line 353, in <module>
    training(
  File "/storage/public/home/2022032005/PycharmProject/CityGaussian/LargeLightGaussian/large_prune_finetune.py", line 109, in training
    gaussian_list, imp_list = prune_list(gaussians, scene, pipe, background, dataset)
  File "/storage/public/home/2022032005/PycharmProject/CityGaussian/LargeLightGaussian/prune.py", line 142, in prune_list
    render_pkg = count_render(viewpoint_cam, gaussians, pipe, background)
  File "/storage/public/home/2022032005/PycharmProject/CityGaussian/LargeLightGaussian/gaussian_renderer/__init__.py", line 209, in count_render
    gaussians_count, important_score, rendered_image, radii = rasterizer(
  File "/storage/public/home/2022032005/miniconda3/envs/city_gaussian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/public/home/2022032005/miniconda3/envs/city_gaussian/lib/python3.10/site-packages/compress_diff_gaussian_rasterization/__init__.py", line 301, in forward
    return rasterize_gaussians(
  File "/storage/public/home/2022032005/miniconda3/envs/city_gaussian/lib/python3.10/site-packages/compress_diff_gaussian_rasterization/__init__.py", line 37, in rasterize_gaussians
    return _RasterizeGaussians.forward_count(
  File "/storage/public/home/2022032005/miniconda3/envs/city_gaussian/lib/python3.10/site-packages/compress_diff_gaussian_rasterization/__init__.py", line 187, in forward_count
    gaussians_count, important_score, num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.count_gaussians(*args)
RuntimeError: numel: integer multiplication overflow

Training progress:   0%|          | 0/30000 [00:03<?, ?it/s]
I don't know what is causing it. Could you please tell me how to fix it, thanks!

**Comment by DekuLiuTesla** [comment]
Hi, @DuHao55, the discussion [here ](https://github.com/graphdeco-inria/gaussian-splatting/issues/24)may help you.

**Comment by DuHao55** [comment]
Thank you, I have resolved it. It might be due to the fact that my compress_diff_gaussian_rasterization wasn't installed correctly, I don't report the error after reinstalling it.
