### ISSUE TITLE
How should the output folder look like?

### ISSUE THREAD

**Issue by nurbanu170399** [DekuLiuTesla/CityGaussian#7]
When i run `bash scripts/run_citygs.sh` i get the error:
```
Output folder: ./output/building_c20_r4 [12/08 20:37:08]
Reading camera 1920/1920 [12/08 20:37:11]
Train cameras: 1920, Test cameras: 0 [12/08 20:37:11]
Traceback (most recent call last):
  File "/home/pc_5053/CityGaussian/data_partition.py", line 151, in <module>
    scene = LargeScene(lp, gaussians, shuffle=False)
  File "/home/pc_5053/CityGaussian/scene/__init__.py", line 168, in __init__
    self.gaussians.load_ply(os.path.join(self.pretrain_path, "point_cloud.ply"))
  File "/home/pc_5053/CityGaussian/scene/gaussian_model.py", line 229, in load_ply
    plydata = PlyData.read(path)
  File "/home/pc_5053/anaconda3/envs/citygs/lib/python3.9/site-packages/plyfile.py", line 401, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/home/pc_5053/anaconda3/envs/citygs/lib/python3.9/site-packages/plyfile.py", line 481, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: 'output/building_coarse/point_cloud/iteration_30000/point_cloud.ply'
GPU 0 is available. Starting training block '0'
Optimizing
Output folder: ./output/building_c20_r4/cells/cell0 [12/08 20:37:14]
Traceback (most recent call last):
  File "/home/pc_5053/CityGaussian/train_large.py", line 309, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/pc_5053/CityGaussian/train_large.py", line 43, in training
    scene = LargeScene(dataset, gaussians)
  File "/home/pc_5053/CityGaussian/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/home/pc_5053/anaconda3/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/building-pixsfm/train/data_partitions/building_c20_r4.npy'
```
So what should my output folder look like? Seems like there is a problem but i could not get it from the instructions. Thank you in advance.

**Comment by DekuLiuTesla** [comment]
Hi, https://github.com/DekuLiuTesla/CityGaussian/issues/5 seems to meet similar problems. We have updated scripts and offered some suggestions in https://github.com/DekuLiuTesla/CityGaussian/issues/5. Please check if they can help you.
